stages:
  collect:
    cmd: python src/collect.py
    deps:
    - src/collect.py
    params:
    - collect.output
    - collect.paperswithcode_token
    outs:
    - data/collect
    frozen: true
  upload:
    cmd: python src/upload.py
    deps:
    - src/upload.py
    params:
    - upload.output
    - upload.supabase_url
    - upload.supabase_key
    outs:
    - data/upload
